// <auto-generated />
using MetalLink.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MetalLink.Infrastructure.Persistence.Migrations;

[DbContext(typeof(MetalLinkDbContext))]
[Migration("20260212193000_AddTicketNumberSequences")]
partial class AddTicketNumberSequences
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // This migration uses raw SQL only.
    }
}
