// <auto-generated />
using System;
using MetalLink.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MetalLink.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MetalLinkDbContext))]
    [Migration("20260203115000_AddTareToReceivingTicketLines")]
    partial class AddTareToReceivingTicketLines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Minimal model definition - just needs to pass validation
            modelBuilder.Entity("MetalLink.Domain.Entities.TicketReceivingLine", b =>
                {
                    b.Property<int>("ReceivingTicketLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("receiving_ticket_line_id")
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReceivingTicketLineId"));

                    b.Property<decimal>("Tare")
                        .HasColumnName("tare")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("ReceivingTicketLineId");

                    b.ToTable("receiving_ticket_lines", "metal_link");
                });

#pragma warning restore 612, 618
        }
    }
}
