// <auto-generated />
using System;
using MetalLink.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MetalLink.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MetalLinkDbContext))]
    [Migration("20260323153307_UpdateDocumentPathsSchema")]
    partial class UpdateDocumentPathsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MetalLink.Domain.Entities.Buyer", b =>
                {
                    b.Property<int>("BuyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("buyer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BuyerId"));

                    b.Property<long?>("AccountNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("account_number");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("id_number");

                    b.Property<int?>("ImagePathId")
                        .HasColumnType("integer")
                        .HasColumnName("image_path_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_taxable");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<int?>("ProductPriceListId")
                        .HasColumnType("integer")
                        .HasColumnName("product_price_list_id");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.HasKey("BuyerId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ImagePathId");

                    b.HasIndex("ProductPriceListId");

                    b.HasIndex("SiteId");

                    b.ToTable("buyers", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<char>("ReceivingSendingFlag")
                        .HasColumnType("character(1)")
                        .HasColumnName("receiving_sending_flag");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vat_number");

                    b.HasKey("CompanyId");

                    b.ToTable("companies", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("country_name");

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CountryId");

                    b.ToTable("countries", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_code");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("currency_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CurrencyId");

                    b.ToTable("currencies", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<long?>("AccountNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("account_number");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("id_number");

                    b.Property<int?>("ImagePathId")
                        .HasColumnType("integer")
                        .HasColumnName("image_path_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCompany")
                        .HasColumnType("boolean")
                        .HasColumnName("is_company");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_taxable");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<int?>("ProductPriceListId")
                        .HasColumnType("integer")
                        .HasColumnName("product_price_list_id");

                    b.Property<int?>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CustomerId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ImagePathId");

                    b.HasIndex("ProductPriceListId");

                    b.HasIndex("SiteId");

                    b.ToTable("customers", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.DocumentPath", b =>
                {
                    b.Property<int>("DocumentPathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("document_path_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentPathId"));

                    b.Property<string>("BbbeeComplianceCertificatePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("bbbee_compliance_certificate_path");

                    b.Property<string>("CipcDocumentPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cipc_document_path");

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("TaxClearanceCertificatePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("tax_clearance_certificate_path");

                    b.Property<string>("TradingLicensePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("trading_license_path");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VatRegistrationCertificatePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("vat_registration_certificate_path");

                    b.HasKey("DocumentPathId");

                    b.ToTable("document_paths", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.ImagePath", b =>
                {
                    b.Property<int>("ImagePathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("image_path_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImagePathId"));

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DriverLicenseImagePath")
                        .HasColumnType("text")
                        .HasColumnName("driver_license_image_path");

                    b.Property<string>("FingerprintImagePath")
                        .HasColumnType("text")
                        .HasColumnName("fingerprint_image_path");

                    b.Property<string>("IdCardImagePath")
                        .HasColumnType("text")
                        .HasColumnName("id_card_image_path");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PhotoImagePath")
                        .HasColumnType("text")
                        .HasColumnName("photo_image_path");

                    b.Property<string>("SignatureImagePath")
                        .HasColumnType("text")
                        .HasColumnName("signature_image_path");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ImagePathId");

                    b.ToTable("image_paths", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Operator", b =>
                {
                    b.Property<int>("OperatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("operator_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OperatorId"));

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("OperatorId");

                    b.ToTable("operators", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.OperatorSetting", b =>
                {
                    b.Property<int>("OperatorSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("operator_setting_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OperatorSettingId"));

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("operator_id");

                    b.Property<int>("SettingId")
                        .HasColumnType("integer")
                        .HasColumnName("setting_id");

                    b.Property<int>("SettingOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("setting_option_id");

                    b.Property<DateTimeOffset>("TimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("TimeUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_updated")
                        .HasDefaultValueSql("now()");

                    b.HasKey("OperatorSettingId");

                    b.HasIndex("CreatedByOperatorId");

                    b.HasIndex("SettingId");

                    b.HasIndex("SettingOptionId");

                    b.HasIndex("OperatorId", "SettingId")
                        .IsUnique()
                        .HasDatabaseName("operator_settings_operator_setting_active_idx")
                        .HasFilter("is_active = true");

                    b.ToTable("operator_settings", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Price", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("price_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriceId"));

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PriceId");

                    b.HasIndex("ProductId");

                    b.ToTable("prices", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("grade");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("MustDeclare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("must_declare");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_name");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ProductId");

                    b.ToTable("products", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.ProductPriceList", b =>
                {
                    b.Property<int>("ProductPriceListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("product_price_list_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductPriceListId"));

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<char>("EntityFlag")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasColumnName("entity_flag");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ProductPriceListDescription")
                        .HasColumnType("text")
                        .HasColumnName("product_price_list_description");

                    b.Property<string>("ProductPriceListName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_price_list_name");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ProductPriceListId");

                    b.HasIndex("CreatedByOperatorId");

                    b.ToTable("product_price_lists", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.ProductPriceListProductPrice", b =>
                {
                    b.Property<int>("ProductPriceListProductPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("product_price_list_product_price_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductPriceListProductPriceId"));

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("ProductPriceListId")
                        .HasColumnType("integer")
                        .HasColumnName("product_price_list_id");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ProductPriceListProductPriceId");

                    b.HasIndex("CreatedByOperatorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductPriceListId", "ProductId", "IsActive")
                        .IsUnique()
                        .HasFilter("is_active = true");

                    b.ToTable("product_price_list_product_prices", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("province_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProvinceId"));

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("province_code");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("province_name");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ProvinceId");

                    b.ToTable("provinces", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Setting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("setting_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SettingId"));

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("SettingDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("setting_description");

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("setting_name");

                    b.Property<DateTimeOffset>("TimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("TimeUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_updated")
                        .HasDefaultValueSql("now()");

                    b.HasKey("SettingId");

                    b.HasIndex("CreatedByOperatorId");

                    b.HasIndex("SettingName")
                        .IsUnique()
                        .HasDatabaseName("settings_setting_name_active_idx")
                        .HasFilter("is_active = true");

                    b.ToTable("settings", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.SettingOption", b =>
                {
                    b.Property<int>("SettingOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("setting_option_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SettingOptionId"));

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("SettingId")
                        .HasColumnType("integer")
                        .HasColumnName("setting_id");

                    b.Property<string>("SettingOptionValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("setting_option_value");

                    b.Property<DateTimeOffset>("TimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("TimeUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_updated")
                        .HasDefaultValueSql("now()");

                    b.HasKey("SettingOptionId");

                    b.HasIndex("CreatedByOperatorId");

                    b.HasIndex("SettingId", "SettingOptionValue")
                        .IsUnique()
                        .HasDatabaseName("setting_options_setting_id_value_active_idx")
                        .HasFilter("is_active = true");

                    b.ToTable("setting_options", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Site", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SiteId"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("city");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DocumentPathId")
                        .HasColumnType("integer")
                        .HasColumnName("document_path_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("integer")
                        .HasColumnName("province_id");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("site_code");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("site_name");

                    b.Property<string>("Suburb")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("suburb");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.HasKey("SiteId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CountryId");

                    b.HasIndex("DocumentPathId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("sites", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.StockMovement", b =>
                {
                    b.Property<int>("StockMovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockMovementId"));

                    b.Property<string>("CounterpartyName")
                        .HasColumnType("text");

                    b.Property<string>("CounterpartyType")
                        .HasColumnType("text");

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityKg")
                        .HasColumnType("numeric");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("text");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.Property<long?>("TicketId1")
                        .HasColumnType("bigint");

                    b.Property<int?>("TicketLineId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPricePerKg")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StockMovementId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SiteId");

                    b.HasIndex("TicketId1");

                    b.ToTable("StockMovement");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.StockMovementReceiving", b =>
                {
                    b.Property<long>("StockMovementReceivingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StockMovementReceivingId"));

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("MovementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProductId1")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityKg")
                        .HasColumnType("numeric");

                    b.Property<long>("SiteId")
                        .HasColumnType("bigint");

                    b.Property<int>("SiteId1")
                        .HasColumnType("integer");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TicketReceivingId")
                        .HasColumnType("bigint");

                    b.Property<int>("TicketReceivingId1")
                        .HasColumnType("integer");

                    b.Property<long?>("TicketReceivingLineId")
                        .HasColumnType("bigint");

                    b.Property<int?>("TicketReceivingLineReceivingTicketLineId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPricePerKg")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StockMovementReceivingId");

                    b.HasIndex("ProductId1");

                    b.HasIndex("SiteId1");

                    b.HasIndex("TicketReceivingId1");

                    b.HasIndex("TicketReceivingLineReceivingTicketLineId");

                    b.ToTable("StockMovementReceiving");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Ticket", b =>
                {
                    b.Property<long>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TicketId"));

                    b.Property<long?>("BuyerId")
                        .HasColumnType("bigint");

                    b.Property<int?>("BuyerId1")
                        .HasColumnType("integer");

                    b.Property<string>("CkNumber")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("CurrencyId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CurrencyId1")
                        .HasColumnType("integer");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CustomerId1")
                        .HasColumnType("integer");

                    b.Property<string>("DeliveryNumber")
                        .HasColumnType("text");

                    b.Property<string>("DriverName")
                        .HasColumnType("text");

                    b.Property<decimal?>("FirstWeightKg")
                        .HasColumnType("numeric");

                    b.Property<string>("ForeignTicket")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("NetWeightKg")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OfmWeighbridgeTicket")
                        .HasColumnType("text");

                    b.Property<long>("OperatorId")
                        .HasColumnType("bigint");

                    b.Property<int>("OperatorId1")
                        .HasColumnType("integer");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("text");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("integer");

                    b.Property<string>("RfidCardNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("SecondWeightKg")
                        .HasColumnType("numeric");

                    b.Property<long>("SiteId")
                        .HasColumnType("bigint");

                    b.Property<int>("SiteId1")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalInclVat")
                        .HasColumnType("numeric");

                    b.Property<string>("TrailerRegistration")
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPricePerKg")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("numeric");

                    b.Property<string>("VehicleRegistration")
                        .HasColumnType("text");

                    b.HasKey("TicketId");

                    b.HasIndex("BuyerId1");

                    b.HasIndex("CurrencyId1");

                    b.HasIndex("CustomerId1");

                    b.HasIndex("OperatorId1");

                    b.HasIndex("ProductId1");

                    b.HasIndex("SiteId1");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.TicketLine", b =>
                {
                    b.Property<long>("TicketLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TicketLineId"));

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProductId1")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalInclVat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPricePerKg")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric");

                    b.HasKey("TicketLineId");

                    b.HasIndex("ProductId1");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketLine");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.TicketReceiving", b =>
                {
                    b.Property<int>("TicketReceivingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("receiving_ticket_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TicketReceivingId"));

                    b.Property<string>("CkNumber")
                        .HasColumnType("text")
                        .HasColumnName("ck_number");

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("DeliveryNumber")
                        .HasColumnType("text")
                        .HasColumnName("delivery_number");

                    b.Property<string>("DriverName")
                        .HasColumnType("text")
                        .HasColumnName("driver_name");

                    b.Property<string>("ForeignTicket")
                        .HasColumnType("text")
                        .HasColumnName("foreign_ticket");

                    b.Property<decimal?>("InitializeWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("initialize_weight_kg");

                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("invoice_number");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("NetWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("net_weight_kg");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OfmWeighbridgeTicket")
                        .HasColumnType("text")
                        .HasColumnName("ofm_weighbridge_ticket");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ticket_number");

                    b.Property<char>("TicketState")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue('C')
                        .HasColumnName("ticket_state");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_type_id");

                    b.Property<string>("TrailerRegistration")
                        .HasColumnType("text")
                        .HasColumnName("trailer_registration");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VehicleRegistration")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_registration");

                    b.HasKey("TicketReceivingId");

                    b.HasIndex("CreatedByOperatorId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("receiving_tickets", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.TicketReceivingLine", b =>
                {
                    b.Property<int>("ReceivingTicketLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("receiving_ticket_line_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReceivingTicketLineId"));

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("FirstWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("first_weight_kg");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("NetWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("net_weight_kg");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("ReceivingTicketId")
                        .HasColumnType("integer")
                        .HasColumnName("receiving_ticket_id");

                    b.Property<decimal?>("SecondWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("second_weight_kg");

                    b.Property<decimal>("Tare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("tare");

                    b.Property<decimal>("UnitPricePerKg")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price_per_kg");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ReceivingTicketLineId");

                    b.HasIndex("CreatedByOperatorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReceivingTicketId");

                    b.ToTable("receiving_ticket_lines", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.TicketSending", b =>
                {
                    b.Property<int>("TicketSendingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sending_ticket_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TicketSendingId"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("integer")
                        .HasColumnName("buyer_id");

                    b.Property<string>("CkNumber")
                        .HasColumnType("text")
                        .HasColumnName("ck_number");

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeliveryNumber")
                        .HasColumnType("text")
                        .HasColumnName("delivery_number");

                    b.Property<string>("DriverName")
                        .HasColumnType("text")
                        .HasColumnName("driver_name");

                    b.Property<string>("ForeignTicket")
                        .HasColumnType("text")
                        .HasColumnName("foreign_ticket");

                    b.Property<decimal?>("InitializeWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("initialize_weight_kg");

                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("invoice_number");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("NetWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("net_weight_kg");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OfmWeighbridgeTicket")
                        .HasColumnType("text")
                        .HasColumnName("ofm_weighbridge_ticket");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ticket_number");

                    b.Property<char>("TicketState")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue('H')
                        .HasColumnName("ticket_state");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_type_id");

                    b.Property<string>("TrailerRegistration")
                        .HasColumnType("text")
                        .HasColumnName("trailer_registration");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VehicleRegistration")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_registration");

                    b.HasKey("TicketSendingId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CreatedByOperatorId");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("sending_tickets", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.TicketSendingLine", b =>
                {
                    b.Property<int>("TicketSendingLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sending_ticket_line_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TicketSendingLineId"));

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("FirstWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("first_weight_kg");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("NetWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("net_weight_kg");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("SecondWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("second_weight_kg");

                    b.Property<decimal>("Tare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("tare");

                    b.Property<int>("TicketSendingId")
                        .HasColumnType("integer")
                        .HasColumnName("sending_ticket_id");

                    b.Property<decimal>("UnitPricePerKg")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price_per_kg");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.HasKey("TicketSendingLineId");

                    b.HasIndex("CreatedByOperatorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TicketSendingId");

                    b.ToTable("sending_ticket_lines", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.TicketType", b =>
                {
                    b.Property<int>("TicketTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_type_id");

                    b.Property<int>("CreatedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("TicketTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ticket_type_name");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.HasKey("TicketTypeId");

                    b.ToTable("ticket_types", "metal_link");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Buyer", b =>
                {
                    b.HasOne("MetalLink.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.ImagePath", "ImagePath")
                        .WithMany()
                        .HasForeignKey("ImagePathId");

                    b.HasOne("MetalLink.Domain.Entities.ProductPriceList", "ProductPriceList")
                        .WithMany()
                        .HasForeignKey("ProductPriceListId");

                    b.HasOne("MetalLink.Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ImagePath");

                    b.Navigation("ProductPriceList");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Customer", b =>
                {
                    b.HasOne("MetalLink.Domain.Entities.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId");

                    b.HasOne("MetalLink.Domain.Entities.ImagePath", "ImagePath")
                        .WithMany()
                        .HasForeignKey("ImagePathId");

                    b.HasOne("MetalLink.Domain.Entities.ProductPriceList", "ProductPriceList")
                        .WithMany()
                        .HasForeignKey("ProductPriceListId");

                    b.HasOne("MetalLink.Domain.Entities.Site", "Site")
                        .WithMany("Customers")
                        .HasForeignKey("SiteId");

                    b.Navigation("Company");

                    b.Navigation("ImagePath");

                    b.Navigation("ProductPriceList");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.OperatorSetting", b =>
                {
                    b.HasOne("MetalLink.Domain.Entities.Operator", "CreatedByOperator")
                        .WithMany()
                        .HasForeignKey("CreatedByOperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.Setting", "Setting")
                        .WithMany()
                        .HasForeignKey("SettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.SettingOption", "SettingOption")
                        .WithMany()
                        .HasForeignKey("SettingOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByOperator");

                    b.Navigation("Operator");

                    b.Navigation("Setting");

                    b.Navigation("SettingOption");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Price", b =>
                {
                    b.HasOne("MetalLink.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.ProductPriceList", b =>
                {
                    b.HasOne("MetalLink.Domain.Entities.Operator", "CreatedByOperator")
                        .WithMany()
                        .HasForeignKey("CreatedByOperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByOperator");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.ProductPriceListProductPrice", b =>
                {
                    b.HasOne("MetalLink.Domain.Entities.Operator", "CreatedByOperator")
                        .WithMany()
                        .HasForeignKey("CreatedByOperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.ProductPriceList", "ProductPriceList")
                        .WithMany("ProductPrices")
                        .HasForeignKey("ProductPriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByOperator");

                    b.Navigation("Product");

                    b.Navigation("ProductPriceList");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Setting", b =>
                {
                    b.HasOne("MetalLink.Domain.Entities.Operator", "CreatedByOperator")
                        .WithMany()
                        .HasForeignKey("CreatedByOperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByOperator");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.SettingOption", b =>
                {
                    b.HasOne("MetalLink.Domain.Entities.Operator", "CreatedByOperator")
                        .WithMany()
                        .HasForeignKey("CreatedByOperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.Setting", "Setting")
                        .WithMany("Options")
                        .HasForeignKey("SettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByOperator");

                    b.Navigation("Setting");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Site", b =>
                {
                    b.HasOne("MetalLink.Domain.Entities.Company", "Company")
                        .WithMany("Sites")
                        .HasForeignKey("CompanyId");

                    b.HasOne("MetalLink.Domain.Entities.Country", "Country")
                        .WithMany("Sites")
                        .HasForeignKey("CountryId");

                    b.HasOne("MetalLink.Domain.Entities.DocumentPath", "DocumentPath")
                        .WithMany()
                        .HasForeignKey("DocumentPathId");

                    b.HasOne("MetalLink.Domain.Entities.Province", "Province")
                        .WithMany("Sites")
                        .HasForeignKey("ProvinceId");

                    b.Navigation("Company");

                    b.Navigation("Country");

                    b.Navigation("DocumentPath");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("MetalLink.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.Ticket", null)
                        .WithMany("StockMovements")
                        .HasForeignKey("TicketId1");

                    b.Navigation("Product");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.StockMovementReceiving", b =>
                {
                    b.HasOne("MetalLink.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.TicketReceiving", "TicketReceiving")
                        .WithMany("StockMovements")
                        .HasForeignKey("TicketReceivingId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.TicketReceivingLine", "TicketReceivingLine")
                        .WithMany()
                        .HasForeignKey("TicketReceivingLineReceivingTicketLineId");

                    b.Navigation("Product");

                    b.Navigation("Site");

                    b.Navigation("TicketReceiving");

                    b.Navigation("TicketReceivingLine");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("MetalLink.Domain.Entities.Buyer", "Buyer")
                        .WithMany("Tickets")
                        .HasForeignKey("BuyerId1");

                    b.HasOne("MetalLink.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId1");

                    b.HasOne("MetalLink.Domain.Entities.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId1");

                    b.HasOne("MetalLink.Domain.Entities.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId1");

                    b.HasOne("MetalLink.Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Currency");

                    b.Navigation("Customer");

                    b.Navigation("Operator");

                    b.Navigation("Product");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.TicketLine", b =>
                {
                    b.HasOne("MetalLink.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Lines")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.TicketReceiving", b =>
                {
                    b.HasOne("MetalLink.Domain.Entities.Operator", "CreatedByOperator")
                        .WithMany()
                        .HasForeignKey("CreatedByOperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.TicketType", "TicketType")
                        .WithMany("TicketsReceiving")
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByOperator");

                    b.Navigation("Customer");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.TicketReceivingLine", b =>
                {
                    b.HasOne("MetalLink.Domain.Entities.Operator", "CreatedByOperator")
                        .WithMany()
                        .HasForeignKey("CreatedByOperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.TicketReceiving", "TicketReceiving")
                        .WithMany("Lines")
                        .HasForeignKey("ReceivingTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByOperator");

                    b.Navigation("Product");

                    b.Navigation("TicketReceiving");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.TicketSending", b =>
                {
                    b.HasOne("MetalLink.Domain.Entities.Buyer", "Buyer")
                        .WithMany("TicketsSending")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.Operator", "CreatedByOperator")
                        .WithMany()
                        .HasForeignKey("CreatedByOperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.TicketType", "TicketType")
                        .WithMany("TicketsSending")
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("CreatedByOperator");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.TicketSendingLine", b =>
                {
                    b.HasOne("MetalLink.Domain.Entities.Operator", "CreatedByOperator")
                        .WithMany()
                        .HasForeignKey("CreatedByOperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetalLink.Domain.Entities.TicketSending", "TicketSending")
                        .WithMany("Lines")
                        .HasForeignKey("TicketSendingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByOperator");

                    b.Navigation("Product");

                    b.Navigation("TicketSending");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Buyer", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("TicketsSending");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Company", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Sites");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Country", b =>
                {
                    b.Navigation("Sites");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.ProductPriceList", b =>
                {
                    b.Navigation("ProductPrices");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Province", b =>
                {
                    b.Navigation("Sites");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Setting", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Site", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.TicketReceiving", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.TicketSending", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MetalLink.Domain.Entities.TicketType", b =>
                {
                    b.Navigation("TicketsReceiving");

                    b.Navigation("TicketsSending");
                });
#pragma warning restore 612, 618
        }
    }
}
