// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace MetalLink.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MetalLinkDbContext))]
    [Migration("20260421000000_AddProductPriceListProductPriceIdToStockLevels")]
    partial class AddProductPriceListProductPriceIdToStockLevels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Migration designer metadata is intentionally minimal for this hand-crafted migration.
            // The model snapshot already exists and provides the current model state.
        }
    }
}
