// <auto-generated />
using MetalLink.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MetalLink.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MetalLinkDbContext))]
    [Migration("20260212190000_DropLegacyInitializeWeightAndAddStockMovementNotes")]
    partial class DropLegacyInitializeWeightAndAddStockMovementNotes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally left empty because this migration uses raw SQL for DB drift fixes.
        }
    }
}
