using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MetalLink.Infrastructure.Persistence.Migrations;

/// <inheritdoc />
public partial class AddOperatorSettingsTables : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.EnsureSchema(name: "metal_link");

        // NOTE:
        // This migration is designed to be safe for an existing database.
        // It ONLY creates the 3 new settings tables + partial unique indexes.
        // We use raw SQL with IF NOT EXISTS to avoid failures when tables/indexes already exist.

        migrationBuilder.Sql(@"
            CREATE TABLE IF NOT EXISTS metal_link.settings (
                setting_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                setting_name character varying(255) NOT NULL,
                setting_description character varying(500) NULL,
                is_active boolean NOT NULL DEFAULT true,
                created_by_operator_id integer NOT NULL,
                time_created timestamp with time zone NOT NULL DEFAULT now(),
                time_updated timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT fk_settings_created_by_operator
                    FOREIGN KEY (created_by_operator_id)
                    REFERENCES metal_link.operators(operator_id)
                    ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS metal_link.setting_options (
                setting_option_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                setting_id integer NOT NULL,
                setting_option_value character varying(255) NOT NULL,
                is_active boolean NOT NULL DEFAULT true,
                created_by_operator_id integer NOT NULL,
                time_created timestamp with time zone NOT NULL DEFAULT now(),
                time_updated timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT fk_setting_options_setting
                    FOREIGN KEY (setting_id)
                    REFERENCES metal_link.settings(setting_id)
                    ON DELETE CASCADE,
                CONSTRAINT fk_setting_options_created_by_operator
                    FOREIGN KEY (created_by_operator_id)
                    REFERENCES metal_link.operators(operator_id)
                    ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS metal_link.operator_settings (
                operator_setting_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                operator_id integer NOT NULL,
                setting_id integer NOT NULL,
                setting_option_id integer NOT NULL,
                is_active boolean NOT NULL DEFAULT true,
                created_by_operator_id integer NOT NULL,
                time_created timestamp with time zone NOT NULL DEFAULT now(),
                time_updated timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT fk_operator_settings_operator
                    FOREIGN KEY (operator_id)
                    REFERENCES metal_link.operators(operator_id)
                    ON DELETE CASCADE,
                CONSTRAINT fk_operator_settings_setting
                    FOREIGN KEY (setting_id)
                    REFERENCES metal_link.settings(setting_id)
                    ON DELETE CASCADE,
                CONSTRAINT fk_operator_settings_setting_option
                    FOREIGN KEY (setting_option_id)
                    REFERENCES metal_link.setting_options(setting_option_id)
                    ON DELETE CASCADE,
                CONSTRAINT fk_operator_settings_created_by_operator
                    FOREIGN KEY (created_by_operator_id)
                    REFERENCES metal_link.operators(operator_id)
                    ON DELETE CASCADE
            );

            -- Helpful non-unique indexes (optional, but good for FK lookups)
            CREATE INDEX IF NOT EXISTS ix_settings_created_by_operator_id
                ON metal_link.settings(created_by_operator_id);

            CREATE INDEX IF NOT EXISTS ix_setting_options_setting_id
                ON metal_link.setting_options(setting_id);

            CREATE INDEX IF NOT EXISTS ix_setting_options_created_by_operator_id
                ON metal_link.setting_options(created_by_operator_id);

            CREATE INDEX IF NOT EXISTS ix_operator_settings_operator_id
                ON metal_link.operator_settings(operator_id);

            CREATE INDEX IF NOT EXISTS ix_operator_settings_setting_id
                ON metal_link.operator_settings(setting_id);

            CREATE INDEX IF NOT EXISTS ix_operator_settings_setting_option_id
                ON metal_link.operator_settings(setting_option_id);

            CREATE INDEX IF NOT EXISTS ix_operator_settings_created_by_operator_id
                ON metal_link.operator_settings(created_by_operator_id);

            -- Partial unique indexes (enforce only one active)
            CREATE UNIQUE INDEX IF NOT EXISTS settings_setting_name_active_idx
                ON metal_link.settings(setting_name)
                WHERE is_active = true;

            CREATE UNIQUE INDEX IF NOT EXISTS setting_options_setting_id_value_active_idx
                ON metal_link.setting_options(setting_id, setting_option_value)
                WHERE is_active = true;

            CREATE UNIQUE INDEX IF NOT EXISTS operator_settings_operator_setting_active_idx
                ON metal_link.operator_settings(operator_id, setting_id)
                WHERE is_active = true;
        ");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        // Drop in dependency order.
        migrationBuilder.Sql(@"
            DROP TABLE IF EXISTS metal_link.operator_settings;
            DROP TABLE IF EXISTS metal_link.setting_options;
            DROP TABLE IF EXISTS metal_link.settings;
        ");
    }
}
