// <auto-generated />
using MetalLink.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MetalLink.Infrastructure.Persistence.Migrations;

[DbContext(typeof(MetalLinkDbContext))]
[Migration("20260217173000_DropSendingTicketHeaderWeightColumns")]
partial class DropSendingTicketHeaderWeightColumns
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // Intentionally empty: this is a drift-fix migration only.
    }
}
