// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using MetalLink.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MetalLink.Infrastructure.Persistence.Migrations
{
    internal partial class TicketEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "MetalLink.Domain.Entities.Ticket",
                typeof(Ticket),
                baseEntityType);

            var ticketId = runtimeEntityType.AddProperty(
                "TicketId",
                typeof(long),
                propertyInfo: typeof(Ticket).GetProperty("TicketId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Ticket).GetField("<TicketId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);
            ticketId.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    (long v1, long v2) => v1 == v2,
                    (long v) => v.GetHashCode(),
                    (long v) => v),
                keyComparer: new ValueComparer<long>(
                    (long v1, long v2) => v1 == v2,
                    (long v) => v.GetHashCode(),
                    (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    (long v1, long v2) => v1 == v2,
                    (long v) => v.GetHashCode(),
                    (long v) => v));
            ticketId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            ticketId.AddAnnotation("Relational:ColumnName", "ticket_id");

            var createdTime = runtimeEntityType.AddProperty(
                "CreatedTime",
                typeof(DateTimeOffset),
                propertyInfo: typeof(Ticket).GetProperty("CreatedTime", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Ticket).GetField("<CreatedTime>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            createdTime.TypeMapping = NpgsqlTimestampTzTypeMapping.Default.Clone(
                comparer: new ValueComparer<DateTimeOffset>(
                    (DateTimeOffset v1, DateTimeOffset v2) => v1.EqualsExact(v2),
                    (DateTimeOffset v) => v.GetHashCode(),
                    (DateTimeOffset v) => v),
                keyComparer: new ValueComparer<DateTimeOffset>(
                    (DateTimeOffset v1, DateTimeOffset v2) => v1.EqualsExact(v2),
                    (DateTimeOffset v) => v.GetHashCode(),
                    (DateTimeOffset v) => v),
                providerValueComparer: new ValueComparer<DateTimeOffset>(
                    (DateTimeOffset v1, DateTimeOffset v2) => v1.EqualsExact(v2),
                    (DateTimeOffset v) => v.GetHashCode(),
                    (DateTimeOffset v) => v),
                clrType: typeof(DateTimeOffset),
                jsonValueReaderWriter: new NpgsqlTimestampTzTypeMapping.NpgsqlJsonTimestampTzDateTimeOffsetReaderWriter());
            createdTime.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            createdTime.AddAnnotation("Relational:ColumnName", "created_time");

            var currencyCode = runtimeEntityType.AddProperty(
                "CurrencyCode",
                typeof(string),
                propertyInfo: typeof(Ticket).GetProperty("CurrencyCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Ticket).GetField("<CurrencyCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 10);
            currencyCode.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                keyComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "character varying(10)",
                    size: 10));
            currencyCode.TypeMapping = ((NpgsqlStringTypeMapping)currencyCode.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
        currencyCode.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
        currencyCode.AddAnnotation("Relational:ColumnName", "currency_code");

        var customerId = runtimeEntityType.AddProperty(
            "CustomerId",
            typeof(long),
            propertyInfo: typeof(Ticket).GetProperty("CustomerId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(Ticket).GetField("<CustomerId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: 0L);
        customerId.TypeMapping = LongTypeMapping.Default.Clone(
            comparer: new ValueComparer<long>(
                (long v1, long v2) => v1 == v2,
                (long v) => v.GetHashCode(),
                (long v) => v),
            keyComparer: new ValueComparer<long>(
                (long v1, long v2) => v1 == v2,
                (long v) => v.GetHashCode(),
                (long v) => v),
            providerValueComparer: new ValueComparer<long>(
                (long v1, long v2) => v1 == v2,
                (long v) => v.GetHashCode(),
                (long v) => v));
        customerId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
        customerId.AddAnnotation("Relational:ColumnName", "customer_id");

        var customerId1 = runtimeEntityType.AddProperty(
            "CustomerId1",
            typeof(long),
            sentinel: 0L);
        customerId1.TypeMapping = LongTypeMapping.Default.Clone(
            comparer: new ValueComparer<long>(
                (long v1, long v2) => v1 == v2,
                (long v) => v.GetHashCode(),
                (long v) => v),
            keyComparer: new ValueComparer<long>(
                (long v1, long v2) => v1 == v2,
                (long v) => v.GetHashCode(),
                (long v) => v),
            providerValueComparer: new ValueComparer<long>(
                (long v1, long v2) => v1 == v2,
                (long v) => v.GetHashCode(),
                (long v) => v));
        customerId1.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var firstWeightKg = runtimeEntityType.AddProperty(
            "FirstWeightKg",
            typeof(decimal?),
            propertyInfo: typeof(Ticket).GetProperty("FirstWeightKg", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(Ticket).GetField("<FirstWeightKg>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            nullable: true);
        firstWeightKg.TypeMapping = NpgsqlDecimalTypeMapping.Default.Clone(
            comparer: new ValueComparer<decimal?>(
                (Nullable<decimal> v1, Nullable<decimal> v2) => v1.HasValue && v2.HasValue && (decimal)v1 == (decimal)v2 || !v1.HasValue && !v2.HasValue,
                (Nullable<decimal> v) => v.HasValue ? ((decimal)v).GetHashCode() : 0,
                (Nullable<decimal> v) => v.HasValue ? (Nullable<decimal>)(decimal)v : default(Nullable<decimal>)),
            keyComparer: new ValueComparer<decimal?>(
                (Nullable<decimal> v1, Nullable<decimal> v2) => v1.HasValue && v2.HasValue && (decimal)v1 == (decimal)v2 || !v1.HasValue && !v2.HasValue,
                (Nullable<decimal> v) => v.HasValue ? ((decimal)v).GetHashCode() : 0,
                (Nullable<decimal> v) => v.HasValue ? (Nullable<decimal>)(decimal)v : default(Nullable<decimal>)),
            providerValueComparer: new ValueComparer<decimal?>(
                (Nullable<decimal> v1, Nullable<decimal> v2) => v1.HasValue && v2.HasValue && (decimal)v1 == (decimal)v2 || !v1.HasValue && !v2.HasValue,
                (Nullable<decimal> v) => v.HasValue ? ((decimal)v).GetHashCode() : 0,
                (Nullable<decimal> v) => v.HasValue ? (Nullable<decimal>)(decimal)v : default(Nullable<decimal>)),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "numeric(18,3)",
                precision: 18,
                scale: 3));
        firstWeightKg.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
        firstWeightKg.AddAnnotation("Relational:ColumnName", "first_weight_kg");
        firstWeightKg.AddAnnotation("Relational:ColumnType", "numeric(18,3)");

        var netWeightKg = runtimeEntityType.AddProperty(
            "NetWeightKg",
            typeof(decimal),
            propertyInfo: typeof(Ticket).GetProperty("NetWeightKg", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(Ticket).GetField("<NetWeightKg>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: 0m);
        netWeightKg.TypeMapping = NpgsqlDecimalTypeMapping.Default.Clone(
            comparer: new ValueComparer<decimal>(
                (decimal v1, decimal v2) => v1 == v2,
                (decimal v) => v.GetHashCode(),
                (decimal v) => v),
            keyComparer: new ValueComparer<decimal>(
                (decimal v1, decimal v2) => v1 == v2,
                (decimal v) => v.GetHashCode(),
                (decimal v) => v),
            providerValueComparer: new ValueComparer<decimal>(
                (decimal v1, decimal v2) => v1 == v2,
                (decimal v) => v.GetHashCode(),
                (decimal v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "numeric(18,3)",
                precision: 18,
                scale: 3));
        netWeightKg.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
        netWeightKg.AddAnnotation("Relational:ColumnName", "net_weight_kg");
        netWeightKg.AddAnnotation("Relational:ColumnType", "numeric(18,3)");

        var notes = runtimeEntityType.AddProperty(
            "Notes",
            typeof(string),
            propertyInfo: typeof(Ticket).GetProperty("Notes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(Ticket).GetField("<Notes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            nullable: true,
            maxLength: 500);
        notes.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
            comparer: new ValueComparer<string>(
                (string v1, string v2) => v1 == v2,
                (string v) => v.GetHashCode(),
                (string v) => v),
            keyComparer: new ValueComparer<string>(
                (string v1, string v2) => v1 == v2,
                (string v) => v.GetHashCode(),
                (string v) => v),
            providerValueComparer: new ValueComparer<string>(
                (string v1, string v2) => v1 == v2,
                (string v) => v.GetHashCode(),
                (string v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "character varying(500)",
                size: 500));
        notes.TypeMapping = ((NpgsqlStringTypeMapping)notes.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
    notes.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
    notes.AddAnnotation("Relational:ColumnName", "notes");

    var operatorId = runtimeEntityType.AddProperty(
        "OperatorId",
        typeof(long),
        propertyInfo: typeof(Ticket).GetProperty("OperatorId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(Ticket).GetField("<OperatorId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        sentinel: 0L);
    operatorId.TypeMapping = LongTypeMapping.Default.Clone(
        comparer: new ValueComparer<long>(
            (long v1, long v2) => v1 == v2,
            (long v) => v.GetHashCode(),
            (long v) => v),
        keyComparer: new ValueComparer<long>(
            (long v1, long v2) => v1 == v2,
            (long v) => v.GetHashCode(),
            (long v) => v),
        providerValueComparer: new ValueComparer<long>(
            (long v1, long v2) => v1 == v2,
            (long v) => v.GetHashCode(),
            (long v) => v));
    operatorId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
    operatorId.AddAnnotation("Relational:ColumnName", "operator_id");

    var operatorId1 = runtimeEntityType.AddProperty(
        "OperatorId1",
        typeof(long),
        sentinel: 0L);
    operatorId1.TypeMapping = LongTypeMapping.Default.Clone(
        comparer: new ValueComparer<long>(
            (long v1, long v2) => v1 == v2,
            (long v) => v.GetHashCode(),
            (long v) => v),
        keyComparer: new ValueComparer<long>(
            (long v1, long v2) => v1 == v2,
            (long v) => v.GetHashCode(),
            (long v) => v),
        providerValueComparer: new ValueComparer<long>(
            (long v1, long v2) => v1 == v2,
            (long v) => v.GetHashCode(),
            (long v) => v));
    operatorId1.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var productDescription = runtimeEntityType.AddProperty(
        "ProductDescription",
        typeof(string),
        propertyInfo: typeof(Ticket).GetProperty("ProductDescription", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(Ticket).GetField("<ProductDescription>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        nullable: true,
        maxLength: 200);
    productDescription.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
        comparer: new ValueComparer<string>(
            (string v1, string v2) => v1 == v2,
            (string v) => v.GetHashCode(),
            (string v) => v),
        keyComparer: new ValueComparer<string>(
            (string v1, string v2) => v1 == v2,
            (string v) => v.GetHashCode(),
            (string v) => v),
        providerValueComparer: new ValueComparer<string>(
            (string v1, string v2) => v1 == v2,
            (string v) => v.GetHashCode(),
            (string v) => v),
        mappingInfo: new RelationalTypeMappingInfo(
            storeTypeName: "character varying(200)",
            size: 200));
    productDescription.TypeMapping = ((NpgsqlStringTypeMapping)productDescription.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
productDescription.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
productDescription.AddAnnotation("Relational:ColumnName", "product_description");

var secondWeightKg = runtimeEntityType.AddProperty(
    "SecondWeightKg",
    typeof(decimal?),
    propertyInfo: typeof(Ticket).GetProperty("SecondWeightKg", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(Ticket).GetField("<SecondWeightKg>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    nullable: true);
secondWeightKg.TypeMapping = NpgsqlDecimalTypeMapping.Default.Clone(
    comparer: new ValueComparer<decimal?>(
        (Nullable<decimal> v1, Nullable<decimal> v2) => v1.HasValue && v2.HasValue && (decimal)v1 == (decimal)v2 || !v1.HasValue && !v2.HasValue,
        (Nullable<decimal> v) => v.HasValue ? ((decimal)v).GetHashCode() : 0,
        (Nullable<decimal> v) => v.HasValue ? (Nullable<decimal>)(decimal)v : default(Nullable<decimal>)),
    keyComparer: new ValueComparer<decimal?>(
        (Nullable<decimal> v1, Nullable<decimal> v2) => v1.HasValue && v2.HasValue && (decimal)v1 == (decimal)v2 || !v1.HasValue && !v2.HasValue,
        (Nullable<decimal> v) => v.HasValue ? ((decimal)v).GetHashCode() : 0,
        (Nullable<decimal> v) => v.HasValue ? (Nullable<decimal>)(decimal)v : default(Nullable<decimal>)),
    providerValueComparer: new ValueComparer<decimal?>(
        (Nullable<decimal> v1, Nullable<decimal> v2) => v1.HasValue && v2.HasValue && (decimal)v1 == (decimal)v2 || !v1.HasValue && !v2.HasValue,
        (Nullable<decimal> v) => v.HasValue ? ((decimal)v).GetHashCode() : 0,
        (Nullable<decimal> v) => v.HasValue ? (Nullable<decimal>)(decimal)v : default(Nullable<decimal>)),
    mappingInfo: new RelationalTypeMappingInfo(
        storeTypeName: "numeric(18,3)",
        precision: 18,
        scale: 3));
secondWeightKg.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
secondWeightKg.AddAnnotation("Relational:ColumnName", "second_weight_kg");
secondWeightKg.AddAnnotation("Relational:ColumnType", "numeric(18,3)");

var siteId = runtimeEntityType.AddProperty(
    "SiteId",
    typeof(long),
    propertyInfo: typeof(Ticket).GetProperty("SiteId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(Ticket).GetField("<SiteId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    sentinel: 0L);
siteId.TypeMapping = LongTypeMapping.Default.Clone(
    comparer: new ValueComparer<long>(
        (long v1, long v2) => v1 == v2,
        (long v) => v.GetHashCode(),
        (long v) => v),
    keyComparer: new ValueComparer<long>(
        (long v1, long v2) => v1 == v2,
        (long v) => v.GetHashCode(),
        (long v) => v),
    providerValueComparer: new ValueComparer<long>(
        (long v1, long v2) => v1 == v2,
        (long v) => v.GetHashCode(),
        (long v) => v));
siteId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
siteId.AddAnnotation("Relational:ColumnName", "site_id");

var siteId1 = runtimeEntityType.AddProperty(
    "SiteId1",
    typeof(long),
    sentinel: 0L);
siteId1.TypeMapping = LongTypeMapping.Default.Clone(
    comparer: new ValueComparer<long>(
        (long v1, long v2) => v1 == v2,
        (long v) => v.GetHashCode(),
        (long v) => v),
    keyComparer: new ValueComparer<long>(
        (long v1, long v2) => v1 == v2,
        (long v) => v.GetHashCode(),
        (long v) => v),
    providerValueComparer: new ValueComparer<long>(
        (long v1, long v2) => v1 == v2,
        (long v) => v.GetHashCode(),
        (long v) => v));
siteId1.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var ticketNumber = runtimeEntityType.AddProperty(
    "TicketNumber",
    typeof(string),
    propertyInfo: typeof(Ticket).GetProperty("TicketNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(Ticket).GetField("<TicketNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    maxLength: 50);
ticketNumber.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
    comparer: new ValueComparer<string>(
        (string v1, string v2) => v1 == v2,
        (string v) => v.GetHashCode(),
        (string v) => v),
    keyComparer: new ValueComparer<string>(
        (string v1, string v2) => v1 == v2,
        (string v) => v.GetHashCode(),
        (string v) => v),
    providerValueComparer: new ValueComparer<string>(
        (string v1, string v2) => v1 == v2,
        (string v) => v.GetHashCode(),
        (string v) => v),
    mappingInfo: new RelationalTypeMappingInfo(
        storeTypeName: "character varying(50)",
        size: 50));
ticketNumber.TypeMapping = ((NpgsqlStringTypeMapping)ticketNumber.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
ticketNumber.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
ticketNumber.AddAnnotation("Relational:ColumnName", "ticket_number");

var ticketType = runtimeEntityType.AddProperty(
    "TicketType",
    typeof(string),
    propertyInfo: typeof(Ticket).GetProperty("TicketType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(Ticket).GetField("<TicketType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    maxLength: 50);
ticketType.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
    comparer: new ValueComparer<string>(
        (string v1, string v2) => v1 == v2,
        (string v) => v.GetHashCode(),
        (string v) => v),
    keyComparer: new ValueComparer<string>(
        (string v1, string v2) => v1 == v2,
        (string v) => v.GetHashCode(),
        (string v) => v),
    providerValueComparer: new ValueComparer<string>(
        (string v1, string v2) => v1 == v2,
        (string v) => v.GetHashCode(),
        (string v) => v),
    mappingInfo: new RelationalTypeMappingInfo(
        storeTypeName: "character varying(50)",
        size: 50));
ticketType.TypeMapping = ((NpgsqlStringTypeMapping)ticketType.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
ticketType.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
ticketType.AddAnnotation("Relational:ColumnName", "ticket_type");

var totalAmount = runtimeEntityType.AddProperty(
    "TotalAmount",
    typeof(decimal),
    propertyInfo: typeof(Ticket).GetProperty("TotalAmount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(Ticket).GetField("<TotalAmount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    sentinel: 0m);
totalAmount.TypeMapping = NpgsqlDecimalTypeMapping.Default.Clone(
    comparer: new ValueComparer<decimal>(
        (decimal v1, decimal v2) => v1 == v2,
        (decimal v) => v.GetHashCode(),
        (decimal v) => v),
    keyComparer: new ValueComparer<decimal>(
        (decimal v1, decimal v2) => v1 == v2,
        (decimal v) => v.GetHashCode(),
        (decimal v) => v),
    providerValueComparer: new ValueComparer<decimal>(
        (decimal v1, decimal v2) => v1 == v2,
        (decimal v) => v.GetHashCode(),
        (decimal v) => v),
    mappingInfo: new RelationalTypeMappingInfo(
        storeTypeName: "numeric(18,2)",
        precision: 18,
        scale: 2));
totalAmount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
totalAmount.AddAnnotation("Relational:ColumnName", "total_amount");
totalAmount.AddAnnotation("Relational:ColumnType", "numeric(18,2)");

var unitPricePerKg = runtimeEntityType.AddProperty(
    "UnitPricePerKg",
    typeof(decimal),
    propertyInfo: typeof(Ticket).GetProperty("UnitPricePerKg", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(Ticket).GetField("<UnitPricePerKg>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    sentinel: 0m);
unitPricePerKg.TypeMapping = NpgsqlDecimalTypeMapping.Default.Clone(
    comparer: new ValueComparer<decimal>(
        (decimal v1, decimal v2) => v1 == v2,
        (decimal v) => v.GetHashCode(),
        (decimal v) => v),
    keyComparer: new ValueComparer<decimal>(
        (decimal v1, decimal v2) => v1 == v2,
        (decimal v) => v.GetHashCode(),
        (decimal v) => v),
    providerValueComparer: new ValueComparer<decimal>(
        (decimal v1, decimal v2) => v1 == v2,
        (decimal v) => v.GetHashCode(),
        (decimal v) => v),
    mappingInfo: new RelationalTypeMappingInfo(
        storeTypeName: "numeric(18,4)",
        precision: 18,
        scale: 4));
unitPricePerKg.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
unitPricePerKg.AddAnnotation("Relational:ColumnName", "unit_price_per_kg");
unitPricePerKg.AddAnnotation("Relational:ColumnType", "numeric(18,4)");

var updatedTime = runtimeEntityType.AddProperty(
    "UpdatedTime",
    typeof(DateTimeOffset),
    propertyInfo: typeof(Ticket).GetProperty("UpdatedTime", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(Ticket).GetField("<UpdatedTime>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
updatedTime.TypeMapping = NpgsqlTimestampTzTypeMapping.Default.Clone(
    comparer: new ValueComparer<DateTimeOffset>(
        (DateTimeOffset v1, DateTimeOffset v2) => v1.EqualsExact(v2),
        (DateTimeOffset v) => v.GetHashCode(),
        (DateTimeOffset v) => v),
    keyComparer: new ValueComparer<DateTimeOffset>(
        (DateTimeOffset v1, DateTimeOffset v2) => v1.EqualsExact(v2),
        (DateTimeOffset v) => v.GetHashCode(),
        (DateTimeOffset v) => v),
    providerValueComparer: new ValueComparer<DateTimeOffset>(
        (DateTimeOffset v1, DateTimeOffset v2) => v1.EqualsExact(v2),
        (DateTimeOffset v) => v.GetHashCode(),
        (DateTimeOffset v) => v),
    clrType: typeof(DateTimeOffset),
    jsonValueReaderWriter: new NpgsqlTimestampTzTypeMapping.NpgsqlJsonTimestampTzDateTimeOffsetReaderWriter());
updatedTime.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
updatedTime.AddAnnotation("Relational:ColumnName", "updated_time");

var key = runtimeEntityType.AddKey(
    new[] { ticketId });
runtimeEntityType.SetPrimaryKey(key);
key.AddAnnotation("Relational:Name", "pk_tickets_ticket_id");

var index = runtimeEntityType.AddIndex(
    new[] { customerId });
index.AddAnnotation("Relational:Name", "tickets_customer_id_idx");

var index0 = runtimeEntityType.AddIndex(
    new[] { customerId1 });

var index1 = runtimeEntityType.AddIndex(
    new[] { operatorId });

var index2 = runtimeEntityType.AddIndex(
    new[] { operatorId1 });

var index3 = runtimeEntityType.AddIndex(
    new[] { siteId });
index3.AddAnnotation("Relational:Name", "tickets_site_id_idx");

var index4 = runtimeEntityType.AddIndex(
    new[] { siteId1 });

var index5 = runtimeEntityType.AddIndex(
    new[] { ticketNumber },
    unique: true);
index5.AddAnnotation("Relational:Name", "tickets_ticket_number_idx");

return runtimeEntityType;
}

public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
{
    var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CustomerId") },
        principalEntityType.FindKey(new[] { principalEntityType.FindProperty("CustomerId") }),
        principalEntityType,
        deleteBehavior: DeleteBehavior.Cascade,
        required: true);

    runtimeForeignKey.AddAnnotation("Relational:Name", "fk_tickets_customer_id_customers");
    return runtimeForeignKey;
}

public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
{
    var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CustomerId1") },
        principalEntityType.FindKey(new[] { principalEntityType.FindProperty("CustomerId") }),
        principalEntityType,
        deleteBehavior: DeleteBehavior.Cascade,
        required: true);

    var customer = declaringEntityType.AddNavigation("Customer",
        runtimeForeignKey,
        onDependent: true,
        typeof(Customer),
        propertyInfo: typeof(Ticket).GetProperty("Customer", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(Ticket).GetField("<Customer>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

    var tickets = principalEntityType.AddNavigation("Tickets",
        runtimeForeignKey,
        onDependent: false,
        typeof(ICollection<Ticket>),
        propertyInfo: typeof(Customer).GetProperty("Tickets", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(Customer).GetField("<Tickets>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

    return runtimeForeignKey;
}

public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
{
    var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("OperatorId") },
        principalEntityType.FindKey(new[] { principalEntityType.FindProperty("OperatorId") }),
        principalEntityType,
        deleteBehavior: DeleteBehavior.Cascade,
        required: true);

    runtimeForeignKey.AddAnnotation("Relational:Name", "fk_tickets_operator_id_operators");
    return runtimeForeignKey;
}

public static RuntimeForeignKey CreateForeignKey4(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
{
    var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("OperatorId1") },
        principalEntityType.FindKey(new[] { principalEntityType.FindProperty("OperatorId") }),
        principalEntityType,
        deleteBehavior: DeleteBehavior.Cascade,
        required: true);

    var @operator = declaringEntityType.AddNavigation("Operator",
        runtimeForeignKey,
        onDependent: true,
        typeof(Operator),
        propertyInfo: typeof(Ticket).GetProperty("Operator", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(Ticket).GetField("<Operator>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

    return runtimeForeignKey;
}

public static RuntimeForeignKey CreateForeignKey5(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
{
    var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("SiteId") },
        principalEntityType.FindKey(new[] { principalEntityType.FindProperty("SiteId") }),
        principalEntityType,
        deleteBehavior: DeleteBehavior.Cascade,
        required: true);

    runtimeForeignKey.AddAnnotation("Relational:Name", "fk_tickets_site_id_sites");
    return runtimeForeignKey;
}

public static RuntimeForeignKey CreateForeignKey6(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
{
    var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("SiteId1") },
        principalEntityType.FindKey(new[] { principalEntityType.FindProperty("SiteId") }),
        principalEntityType,
        deleteBehavior: DeleteBehavior.Cascade,
        required: true);

    var site = declaringEntityType.AddNavigation("Site",
        runtimeForeignKey,
        onDependent: true,
        typeof(Site),
        propertyInfo: typeof(Ticket).GetProperty("Site", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(Ticket).GetField("<Site>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

    return runtimeForeignKey;
}

public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
{
    runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
    runtimeEntityType.AddAnnotation("Relational:Schema", "metal_link");
    runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
    runtimeEntityType.AddAnnotation("Relational:TableName", "tickets");
    runtimeEntityType.AddAnnotation("Relational:ViewName", null);
    runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

    Customize(runtimeEntityType);
}

static partial void Customize(RuntimeEntityType runtimeEntityType);
}
}
