[build]
nixPkgs = ["dotnet-sdk"]

[env]
DOTNET_SDK_VERSION = "8.0"

[phases.install]
cmds = ["dotnet restore MetalLink.sln"]

[phases.build]
cmds = ["dotnet publish MetalLink.Api/MetalLink.Api.csproj --no-restore -c Release -o out"]

[start]
cmd = "./out/MetalLink.Api"
