services:
  - type: web
    name: MetalLink API
    env: docker
    branch: master
    dockerfilePath: Dockerfile
    autoDeploy: true
    plan: starter
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: "8080"
      - key: FileStorage:BucketName
        value: metal-link-storage-eu-540034107961-eu-central-1-an
      - key: FileStorage:UseMinio
        value: "false"
      - key: FileStorage:Region
        value: eu-central-1
      - key: FileStorage:AccessKey
        value: "<AWS_ACCESS_KEY_ID>"
      - key: FileStorage:SecretKey
        value: "<AWS_SECRET_ACCESS_KEY>"
      - key: AWS_ACCESS_KEY_ID
        value: "<AWS_ACCESS_KEY_ID>"
      - key: AWS_SECRET_ACCESS_KEY
        value: "<AWS_SECRET_ACCESS_KEY>"
    healthCheckPath: /api/health/db

databases:
  - name: MetalLink DB
    plan: starter
    postgresVersion: "15"
    databaseName: metal_link_dev
